id: AFB540E94
title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
  White and Red Amitāyus'
type: translation
pechas:
- IBF888796
- IE022EEB0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:02.558313
  last_modified_at: 2023-01-04 12:15:02.558322
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IBF888796/4135: B21B
  IE022EEB0/748A: B21B
